### PR TITLE
Allows the behaviour of command sending to be overridden

### PR DESCRIPTION
**Pull request by iainmckay**
We have the need to alter the command name dynamically based on some data. This PR allows us to do that while keeping the general behaviour (i.e. adding the delay).

### CODE REVIEW

**Review by prolic — COMMENTED** [review]
I am kind of against this change and think you may use a custom message producer in that case. What do you think @codeliner?

**Comment by iainmckay** [comment]
We could certainly duplicate this producer to make our changes if this is the general feeling.

**Comment by codeliner** [comment]
What is the command name in this case? It is not the command message name of the prooph message, or?

/cc @makasim

**Comment by iainmckay** [comment]
In this case we're using the command name to place commands in difference queues as enqueue is overwriting the queue name in `RouterProcessor` ([here](https://github.com/php-enqueue/enqueue-dev/blob/56e231afe38f54889f8f89e633dbd508b5ac3fc0/pkg/enqueue/Client/RouterProcessor.php#L111)).

We have separate worker processes processing these queues.

We're also using this PR to do a couple of other things.

**Comment by makasim** [comment]
> It is not the command message name of the prooph message, or?

@codeliner nope it is Enqueue's command name, define a processor to be called on consumer side.

> In this case we're using the command name to place commands in difference queues as enqueue is overwriting the queue name in RouterProcessor

@iainmckay  there is a possibility to register this processor so the messages do not go through the router but go directly to the destination queue. Does it solve your issue?

**Comment by iainmckay** [comment]
@makasim I think it would, do you know how to do this? I'm taking a deeper dive in to their code now

**Comment by codeliner** [comment]
thanks @makasim . that was the detail I was looking for.

Yeah ok, so I'm also against the change. If the suggestion by @makasim does not work we should think about other possibilities like some sort of composition, but most prooph classes are final with private props for a good reason and we should keep it like that.

**Comment by makasim** [comment]
@iainmckay add those options to your enqueue  DI tag: https://github.com/php-enqueue/enqueue-elastica-bundle/blob/7c05c55b1667f9cae98325257ba24fc101f87f97/Async/ElasticaPopulateProcessor.php#L73-L75

**Comment by iainmckay** [comment]
@codeliner That's fair enough, it did feel wrong removing the final keyword.

@makasim That did the trick, we'll find alternative methods to achieve the other things we were doing with this PR

Thanks for your time guys

**Pull request closed without merging**
